baseURL = 'https://paco-folli.vercel.app/'
title = 'paco.folli'
theme = ["PaperMod"]

[params]
env = 'production'
description = "Paco Folli - https://paco-folli.vercel.app"
author = "Giacomo Folii"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = false
images = ["/images/profile.jpg"]
ShareButtons = ["linkedin", "twitter"]

[params.profileMode]
enabled = true
title = "Giacomo Folli"
subtitle = "Fullstack developer & some other weird things"
imageUrl = "/images/profile.jpg"
imageTitle = "Giacomo Folli"
imageWidth = 170
imageHeight = 170

[[params.socialIcons]]
name = "Soundcloud"
url = "https://soundcloud.com/itspacoti"

[[params.socialIcons]]
name = "Instagram"
url = "https://www.instagram.com/paco.nocap"

[[params.socialIcons]]
name = "Mastodon"
url = "https://mastodon.uno/@giacomofolli"

[[params.socialIcons]]
name = "Youtube"
url = "https://www.youtube.com/@EnricoSpazio"

[[params.socialIcons]]
name = "Substack"
url = "https://altrove.substack.com/"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "search"
name = "search"
url = "/search"
weight = 30
